name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ['3.8', '3.9', '3.10']
        django: ['3.2', '4.0']
        wagtail: ['2.16', '3.0', '4.0']
        include:
          - python: '3.7'
            django: '3.2'
            wagtail: '2.15'
          - python: '3.8'
            django: '3.2'
            wagtail: '2.15'
          - python: '3.9'
            django: '3.2'
            wagtail: '2.15'
          - python: '3.10'
            django: '3.2'
            wagtail: '2.15'
          - python: '3.8'
            django: '4.1'
            wagtail: '4.0'
          - python: '3.9'
            django: '4.1'
            wagtail: '4.0'
          - python: '3.10'
            django: '4.1'
            wagtail: '4.0'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install --no-interaction --no-root

      - name: Run Tests
        run: |
          python -m pip install --upgrade pip tox
      - name: Test with tox
        run: |
            tox
        env:
            TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}
